### ISSUE TITLE
Documentation tag @return leads to skip the documentation analysis for a method

### ISSUE THREAD

**Issue by mguthmuller** [rrrene/inch#30]
I absolutely don't know why but for a simple method with no parameter, when I put the above yard documentation, inch doesn't generate any information about the documentation grade. It seems that the method is not analyzed (even with --pedantic). If I remove the line with @return, it works !

Yard documentation:
\# Define tags to track, including tags added on command line
\# @return [String] regexp pattern

Do you have any idea about this curious behavior ?

**Comment by rrrene** [comment]
Three things to check:

1. What does `inch list --all` output? 
2. Maybe you just documented everything?
3. Can you link to the code in question or is it closed source?

**Comment by mguthmuller** [comment]
My mistake! If I do `inch list --all`, I see my method whose documentation is considered as "Seems really good". So, if I understand, without `list --all`, inch only displays parts of code which need more documentation ?

**Comment by rrrene** [comment]
`inch` is the same as `inch suggest` which shows you suggestions where your docs could be improved. In your case, Inch could not find anything to suggest :+1: 

It is important to understand that `inch suggest` prioritizes code objects, i.e. it decides which things are more important to document than others. You can read about it [in this part of the README](https://github.com/rrrene/inch#priorities--).

`inch list`simply lists everything Inch found, regardless of priority.

**Comment by mguthmuller** [comment]
Ok, thanks for your detailed answer.
