### ISSUE TITLE
Support for the Crystal Programming Language

### ISSUE THREAD

**Issue by keplersj** [rrrene/inch#38]
I'd love to help implement this too, but I don't know where to start

**Comment by rrrene** [comment]
Would love to support it. Is there an option for `crystal doc` so it outputs JSON instead of HTML?

**Comment by keplersj** [comment]
I don't think there is currently.

/cc @asterite

**Comment by asterite** [comment]
No, but a JSON output could be done. In fact this output could maybe be used to generate ctags and other stuff. Basically output the whole classes + methods + docs in JSON. Feel free to open an enhancement in Crystal's repo. Implementing it shouldn't be hard, the code that generates the docs is more or less nice :-)

**Comment by straight-shoota** [comment]
crystal-lang/crystal#4746 has been merged to Crystal master with JSON output.

**Comment by faustinoaq** [comment]
> Would love to support it. Is there an option for crystal doc so it outputs JSON instead of HTML?

@rrrene Any idea how to help with this? I think crystal docs already has support for JSON output :wink:

**Comment by Jens0512** [comment]
And with https://github.com/crystal-lang/crystal/pull/6982 merged, the stage is set!

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
