### ISSUE TITLE
Incorrect support for RDoc virtual methods

### ISSUE THREAD

**Issue by halostatue** [rrrene/inch#41]
Re: [U] [MIME::Type#preferred_extension](http://inch-ci.org/github/mime-types/ruby-mime-types/revision/b0a4457d/code_object/2645739?branch=qa-tool) in [mime-types/ruby-mime-types](http://inch-ci.org/github/mime-types/ruby-mime-types) Also probably related to #28 and #40.

I’m not sure if you’ll be able to make this work properly since YARD deliberately does not support a number of RDoc features (including proper use of the `:nodoc:` directive, because it doesn’t believe gem authors are correct when they say `:nodoc:`), but most troublesome to me is its inability to support virtual method documentation. Inch reports that `MIME::Type#preferred_extension` is undocumented, which is _technically_ correct, but with virtual method documentation it is incorrect.

You can see this throughout the mime-types code, but specifically at [lib/mime/type.rb:243-265](https://github.com/mime-types/ruby-mime-types/blob/qa-tool/lib/mime/type.rb#L243-L265). Here, I have specifically created a virtual method documentation for `attr_accessor :preferred_extension` and then I have implemented `preferred_extension` and `preferred_extension=`. The former I suppressed the documentation on; the latter I `:nodoc:`ed. YARD ignores everything here, and I suspect it causes inch to do the same.

I do this because I want this documented as an `attr_accessor`, not as two methods (I realize that YARD doesn’t really distinguish between the two, but RDoc does and I like that).

Thanks for a great tool—I’m enjoying using it despite the problems I’m having getting it to recognize the documentation I have written, and I think it’s improving the documentation I have (which was pretty good to begin with, IMO).

**Comment by rrrene** [comment]
Hi Austin,

thx for writing this up. As you already deduced correctly, Inch relies heavily on YARD to do its parsing. I will have to set aside some time to figure out all the stuff you pointed out and see if we can find a solution which (hopefully) does not require us to write our own parser.

That said, please keep these bug reports coming. I really appreciate the time you put into them! :+1: I firmly believe that documenting the missing/defunct parts of Inch is very important. Bug reporting is a big (and often unrewarding) part of Open Source in general, so "Thanks!" for your work on this.

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.

**Comment by halostatue** [comment]
Not using inch at the moment, but the fundamental bug is in the [intentional incompatibility](https://github.com/lsegal/yard/issues/1254#issuecomment-503740137) with RDoc. This is the main reason that I’ve never actually looked at YARD for any sort of serious documentation, because it introduced incompatibility with the standard documentation tool for no good reason at all.

(I suspect that most of YARD could have been written as RDoc extensions.)
