### ISSUE TITLE
Exclude Frozen Ruby String Declarations

### ISSUE THREAD

**Issue by thegranddesign** [rrrene/inch#46]
There are a consistent number of files which get a grade of "A" even though all they have is a:

```ruby
# frozen_string_literal: true
```

[Example here](http://inch-ci.org/github/rails/rails/revision/1ba84126/code_object/136985148?branch=master)

comment in them.  Since this is a very standard thing to have in your Ruby 2.x files, I think it should be explicitly excluded from documentation.  Preferably the inch configuration would allow for specification of regexes which match to be excluded.

**Comment by rrrene** [comment]
Thx for reporting this! I will a "Help wanted" tag to this :+1:

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
