### ISSUE TITLE
Do not count TODO, FIXME, etc. comments

### ISSUE THREAD

**Issue by reitzig** [rrrene/inch#50]
I was surprised to find that Inch CI attests my brand new and barely documented gem an excellent doc health. This is because Inch is completely satisfied with TODO comments:

```ruby
# TODO: document
class Foo
    # TODO: document
    def bar
        puts "undocumented!"
    end
end
```

Arguably, this should count as completely documented.

I propose that "label" comments such as `# TODO` should be ignored by inch.

**Comment by rrrene** [comment]
> I propose that "label" comments such as # TODO should be ignored by inch.

I see your point. But I am hestitant to ignoring the completely. A thoughtful `TODO` or `NOTE` comment is IMHO not the same as "undocumented".

Can we find some "middleground" here?

**Comment by reitzig** [comment]
Quite right. For me, TODO comments are developer notes and should never be in a user/customer-facing API doc; I'm sure other people have other needs.

It's your tool, so you are certainly the better judge of where this fits in. 
There are four grades to choose from; if not A and not Undocumented, one of B and C should do the job? I don't have enough experience with Inch to say which one fits better for the general populace. My vote would be for C, maybe with a special message like "you wanted to do something here?"

**Comment by reitzig** [comment]
If you can point me in a direction, I may be tempted to have a go at it myself. Not sure where to start looking for the relevant code though. :'D

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
