### ISSUE TITLE
Inch failing to create page

### ISSUE THREAD

**Issue by optimizasean** [rrrene/inch#53]
Inch web is failing to build my ruby gem (dtg).  I have attached screenshots of the pages I navigated through.  I added inch to my GitHub as well by signing in with it.  Also, forgot to add, one of my other inch builds for dtg built for well over 3000 seconds before I accidentally closed the browser and I realized I did not have the link anymore.

https://github.com/optimizasean/dtg

(only have one branch: master)

I just made this project for myself and a few others and saw how much trouble it was and figured I would put it open source so others could benefit from it as well.  I really want to get the badge and data to help me assess documentation.  Thanks!

![Sync Page](https://user-images.githubusercontent.com/8909476/61502764-dbc40a00-a970-11e9-9a9d-593f8640fbbb.png)
![Build List](https://user-images.githubusercontent.com/8909476/61502765-dbc40a00-a970-11e9-98ef-93a79cada40c.png)
![Inch Builds](https://user-images.githubusercontent.com/8909476/61502766-dbc40a00-a970-11e9-88bc-3e13e4f5dc11.png)

**Comment by SolarisFlare** [comment]
I left it running overnight and here are my results:
![Inch Overnight](https://user-images.githubusercontent.com/8909476/61553858-1ff9ed80-a9f7-11e9-8fad-53e20289eed4.png)

**Comment by SolarisFlare** [comment]
Checking in, I left it running until a day or two ago and no luck so I closed my browser to restart my computer

**Comment by SolarisFlare** [comment]
So inch just up and worked today, see my status on the above issue.  Looks like I got the badge and everything seems as I expected it.  But for like a 2 week time it seems like there may be some either verbosity required or fixes necessary to improve the performance.

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😞 

Please feel free to re-open this issue at your discretion.

**Comment by optimizasean** [comment]
Oh heck I forgot about this ummmm sure probably has been resolved somewhere by now I think. Not actually sure what project I was working on at that time... 😆
